name: Dependabot Auto Merge

on:
  pull_request:
    branches: [main]

jobs:
  call:
    if: github.actor == 'dependabot[bot]'
    uses: ryoooosk/reusable-workflows/.github/workflows/dependabot-auto-merge.yml@main
    permissions:
      pull-requests: write
      contents: write
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
