name: server-ci

on:
  pull_request:

concurrency:
  group: server-ci-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  server-ci:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - run: pnpm ci
      - run: pnpm typecheck
      - run: pnpm biome:ci
